name: shohnaat_mobile
description: "Shohnaat Logistics - Cross-Platform Mobile Application for Riders, Merchants, and Customers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management & Architecture
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Networking & HTTP
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0

  # Storage & Offline Cache
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Typography & Icons
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0

  # Hardware & Native Features
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  signature: ^5.5.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
